export const BOOKS = [
  { code: "MAT", name: "Matthew", file: "41MATMSB_int.usx" },
  { code: "MRK", name: "Mark", file: "42MRKMSB_int.usx" },
  { code: "LUK", name: "Luke", file: "43LUKMSB_int.usx" },
  { code: "JHN", name: "John", file: "44JHNMSB_int.usx" },
  { code: "ACT", name: "Acts", file: "45ACTMSB_int.usx" },
  { code: "ROM", name: "Romans", file: "46ROMMSB_int.usx" },
  { code: "1CO", name: "1 Corinthians", file: "471COMSB_int.usx" },
  { code: "2CO", name: "2 Corinthians", file: "482COMSB_int.usx" },
  { code: "GAL", name: "Galatians", file: "49GALMSB_int.usx" },
  { code: "EPH", name: "Ephesians", file: "50EPHMSB_int.usx" },
  { code: "PHP", name: "Philippians", file: "51PHPMSB_int.usx" },
  { code: "COL", name: "Colossians", file: "52COLMSB_int.usx" },
  { code: "1TH", name: "1 Thessalonians", file: "531THMSB_int.usx" },
  { code: "2TH", name: "2 Thessalonians", file: "542THMSB_int.usx" },
  { code: "1TI", name: "1 Timothy", file: "551TIMSB_int.usx" },
  { code: "2TI", name: "2 Timothy", file: "562TIMSB_int.usx" },
  { code: "TIT", name: "Titus", file: "57TITMSB_int.usx" },
  { code: "PHM", name: "Philemon", file: "58PHMMSB_int.usx" },
  { code: "HEB", name: "Hebrews", file: "59HEBMSB_int.usx" },
  { code: "JAS", name: "James", file: "60JASMSB_int.usx" },
  { code: "1PE", name: "1 Peter", file: "611PEMSB_int.usx" },
  { code: "2PE", name: "2 Peter", file: "622PEMSB_int.usx" },
  { code: "1JN", name: "1 John", file: "631JNMSB_int.usx" },
  { code: "2JN", name: "2 John", file: "642JNMSB_int.usx" },
  { code: "3JN", name: "3 John", file: "653JNMSB_int.usx" },
  { code: "JUD", name: "Jude", file: "66JUDMSB_int.usx" },
  { code: "REV", name: "Revelation", file: "67REVMSB_int.usx" },
];
